version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "p55w0rd!"
      MSSQL_PID: "Developer"
    ports:
      - "14340:1433"
